use serde::{Deserialize, Serialize};

/// Represents the actor in a conversation turn.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Role {
    /// System directives, persona definitions, and instructions for the model.
    System,
    /// User input provided to the agent.
    User,
    /// Model output, including text responses and requested tool calls.
    Assistant,
    /// Results returned by executed tools.
    Tool,
}

/// A single message turn within the conversation history.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Message {
    /// The role of the author of this message.
    pub role: Role,

    /// The textual content of the message. Optional when only tool calls are generated.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,

    /// Tool calls generated by the assistant turn, if any.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_calls: Option<Vec<ToolCall>>,

    /// Tool call identifier associated with this result message (required for `Role::Tool`).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_call_id: Option<String>,
}

impl Message {
    /// Creates a new system message with the given content.
    pub fn system(content: impl Into<String>) -> Self {
        Self {
            role: Role::System,
            content: Some(content.into()),
            tool_calls: None,
            tool_call_id: None,
        }
    }

    /// Creates a new user message with the given content.
    pub fn user(content: impl Into<String>) -> Self {
        Self {
            role: Role::User,
            content: Some(content.into()),
            tool_calls: None,
            tool_call_id: None,
        }
    }

    /// Creates a new assistant text message with the given content.
    pub fn assistant(content: impl Into<String>) -> Self {
        Self {
            role: Role::Assistant,
            content: Some(content.into()),
            tool_calls: None,
            tool_call_id: None,
        }
    }

    /// Creates a new assistant message containing requested tool calls.
    pub fn assistant_tool_calls(tool_calls: Vec<ToolCall>) -> Self {
        Self {
            role: Role::Assistant,
            content: None,
            tool_calls: Some(tool_calls),
            tool_call_id: None,
        }
    }

    /// Creates a new tool result message responding to a specific `tool_call_id`.
    pub fn tool(content: impl Into<String>, tool_call_id: impl Into<String>) -> Self {
        Self {
            role: Role::Tool,
            content: Some(content.into()),
            tool_calls: None,
            tool_call_id: Some(tool_call_id.into()),
        }
    }
}

/// Represents a function/tool invocation request emitted by the LLM.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ToolCall {
    /// Unique identifier for this tool call.
    pub id: String,

    /// Type of tool call. Defaults to `"function"`.
    #[serde(default = "default_tool_type")]
    pub r#type: String,

    /// Function call details containing name and serialized JSON arguments.
    pub function: FunctionCall,
}

fn default_tool_type() -> String {
    "function".to_string()
}

impl ToolCall {
    /// Creates a new tool call with the default type `"function"`.
    pub fn new(
        id: impl Into<String>,
        name: impl Into<String>,
        arguments: impl Into<String>,
    ) -> Self {
        Self {
            id: id.into(),
            r#type: default_tool_type(),
            function: FunctionCall {
                name: name.into(),
                arguments: arguments.into(),
            },
        }
    }
}

/// Details of a function call requested by the LLM.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct FunctionCall {
    /// Name of the tool or function to execute.
    pub name: String,

    /// Raw unparsed JSON arguments string produced by the LLM.
    pub arguments: String,
}

/// Definition of an available tool advertised to the LLM during prompt construction.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ToolDefinition {
    /// Type of tool definition. Typically `"function"`.
    pub r#type: String,

    /// Function schema details.
    pub function: FunctionDefinition,
}

impl ToolDefinition {
    /// Creates a new function tool definition.
    pub fn function(
        name: impl Into<String>,
        description: impl Into<String>,
        parameters: serde_json::Value,
    ) -> Self {
        Self {
            r#type: "function".to_string(),
            function: FunctionDefinition {
                name: name.into(),
                description: description.into(),
                parameters,
            },
        }
    }
}

/// Function schema parameters advertised to the LLM.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct FunctionDefinition {
    /// Name of the function.
    pub name: String,

    /// Natural language description of what the function does.
    pub description: String,

    /// JSON Schema object defining input parameter types and requirements.
    pub parameters: serde_json::Value,
}

/// Internal representation of a tool execution outcome.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ToolResult {
    /// Corresponding tool call identifier.
    pub tool_call_id: String,

    /// Result payload (output string or error explanation).
    pub content: String,

    /// Indicates whether the execution encountered a runtime or parsing failure.
    pub is_error: bool,
}

impl ToolResult {
    /// Creates a successful tool execution result.
    pub fn success(tool_call_id: impl Into<String>, content: impl Into<String>) -> Self {
        Self {
            tool_call_id: tool_call_id.into(),
            content: content.into(),
            is_error: false,
        }
    }

    /// Creates an error tool execution result.
    pub fn error(tool_call_id: impl Into<String>, error_message: impl Into<String>) -> Self {
        Self {
            tool_call_id: tool_call_id.into(),
            content: error_message.into(),
            is_error: true,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn test_role_serialization() {
        assert_eq!(serde_json::to_string(&Role::System).unwrap(), "\"system\"");
        assert_eq!(serde_json::to_string(&Role::User).unwrap(), "\"user\"");
        assert_eq!(
            serde_json::to_string(&Role::Assistant).unwrap(),
            "\"assistant\""
        );
        assert_eq!(serde_json::to_string(&Role::Tool).unwrap(), "\"tool\"");

        assert_eq!(
            serde_json::from_str::<Role>("\"system\"").unwrap(),
            Role::System
        );
        assert_eq!(
            serde_json::from_str::<Role>("\"user\"").unwrap(),
            Role::User
        );
        assert_eq!(
            serde_json::from_str::<Role>("\"assistant\"").unwrap(),
            Role::Assistant
        );
        assert_eq!(
            serde_json::from_str::<Role>("\"tool\"").unwrap(),
            Role::Tool
        );
    }

    #[test]
    fn test_message_constructors_and_serialization() {
        let msg_sys = Message::system("System instruction");
        let json_sys = serde_json::to_value(&msg_sys).unwrap();
        assert_eq!(
            json_sys,
            json!({
                "role": "system",
                "content": "System instruction"
            })
        );

        let msg_user = Message::user("Hello agent");
        let json_user = serde_json::to_value(&msg_user).unwrap();
        assert_eq!(
            json_user,
            json!({
                "role": "user",
                "content": "Hello agent"
            })
        );

        let tool_call = ToolCall {
            id: "call_abc123".to_string(),
            r#type: "function".to_string(),
            function: FunctionCall {
                name: "calculate".to_string(),
                arguments: "{\"expression\":\"2+2\"}".to_string(),
            },
        };
        let msg_assistant_tool = Message::assistant_tool_calls(vec![tool_call]);
        let json_assistant = serde_json::to_value(&msg_assistant_tool).unwrap();
        assert_eq!(
            json_assistant,
            json!({
                "role": "assistant",
                "tool_calls": [
                    {
                        "id": "call_abc123",
                        "type": "function",
                        "function": {
                            "name": "calculate",
                            "arguments": "{\"expression\":\"2+2\"}"
                        }
                    }
                ]
            })
        );

        let msg_tool = Message::tool("4", "call_abc123");
        let json_tool = serde_json::to_value(&msg_tool).unwrap();
        assert_eq!(
            json_tool,
            json!({
                "role": "tool",
                "content": "4",
                "tool_call_id": "call_abc123"
            })
        );
    }

    #[test]
    fn test_tool_definition_serialization() {
        let tool_def = ToolDefinition::function(
            "calculator",
            "Evaluates arithmetic expressions",
            json!({
                "type": "object",
                "properties": {
                    "expression": { "type": "string" }
                },
                "required": ["expression"]
            }),
        );

        let val = serde_json::to_value(&tool_def).unwrap();
        assert_eq!(val["type"], "function");
        assert_eq!(val["function"]["name"], "calculator");
        assert_eq!(
            val["function"]["description"],
            "Evaluates arithmetic expressions"
        );
        assert_eq!(val["function"]["parameters"]["required"][0], "expression");
    }

    #[test]
    fn test_tool_result_constructors() {
        let res_ok = ToolResult::success("call_1", "Output text");
        assert!(!res_ok.is_error);
        assert_eq!(res_ok.tool_call_id, "call_1");
        assert_eq!(res_ok.content, "Output text");

        let res_err = ToolResult::error("call_2", "Execution failed");
        assert!(res_err.is_error);
        assert_eq!(res_err.tool_call_id, "call_2");
        assert_eq!(res_err.content, "Execution failed");
    }

    #[test]
    fn test_deserialization_roundtrip() {
        let raw_json = r#"{
            "role": "assistant",
            "content": null,
            "tool_calls": [
                {
                    "id": "call_999",
                    "type": "function",
                    "function": {
                        "name": "echo",
                        "arguments": "{\"message\":\"test\"}"
                    }
                }
            ]
        }"#;

        let msg: Message = serde_json::from_str(raw_json).unwrap();
        assert_eq!(msg.role, Role::Assistant);
        assert!(msg.content.is_none());
        assert!(msg.tool_calls.is_some());
        let calls = msg.tool_calls.unwrap();
        assert_eq!(calls.len(), 1);
        assert_eq!(calls[0].id, "call_999");
        assert_eq!(calls[0].function.name, "echo");
    }
}
